version: '3'
services:
    mongo:
        container_name: mongo
        image: mongo:latest
        restart: always
        volumes:
            - ./db:/data/db
        expose:
            - 27017
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=SUPERDUPERSECRET
        command: mongod --auth

    mongo-express:
        container_name: mongo-express
        image: mongo-express:latest
        restart: always
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_BASICAUTH_USERNAME=user
            - ME_CONFIG_BASICAUTH_PASSWORD=SUPERSECRET
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=SUPERDUPERSECRET
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_MONGODB_PORT=27017
        links:
            - mongo
